services:
    catalogdb:
      container_name: catalogDb
      environment:
        - POSTGRES_DB=catalogdb
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      restart: always
      ports:
        - "5433:5432"
      volumes:
        - postgres_catalog:/var/lib/postgresql/data